REST order search documentation
plentymarkets/plenty-developers-docs pull request #91
Opened 2022-01-06 08:30 UTC by raphael-adam

https://plentymarkets.kanbanize.com/ctrl_board/75/cards/222243/details/

@plentymarkets/team-order-payment

https://github.com/plentymarkets/module-order/pull/1352

2022-01-06 09:55 UTC, estafilarakis approved these changes

2022-01-06 12:04 UTC, MKanitz requested changes

2022-01-06 12:38 UTC, estafilarakis submitted a review, later dismissed

2022-01-06 13:24 UTC, MKanitz approved these changes

2022-01-07 13:37 UTC, jawendel requested changes

2022-01-07 13:37 UTC, jawendel commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +This is an example how to filter all orders with a status less than 7:
```suggestion
This is an example how to filter all orders in a status less than 7:
```

2022-01-07 13:37 UTC, jawendel commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +Data given as query string parameters must be URL encoded. So in this example the string `2021-12-22T00:00:00+01:00` must be encoded as `2021-12-22T00%3A00%3A00%2B01%3A00`. This is not necessary when
```suggestion
Data given as query string parameters have to be URL encoded. So in this example the string `2021-12-22T00:00:00+01:00` must be encoded as `2021-12-22T00%3A00%3A00%2B01%3A00`. This is not necessary when sending the filters in the request body.
```

2022-01-10 08:14 UTC, raphael-adam commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +To search for single values, the filters can just be defined like this:
```suggestion
To search for single values, the filters can simply be defined like this:
```

2022-01-10 08:19 UTC, raphael-adam commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +To search for single values, the filters can just be defined like this:
Ich habe hier "einfach" gemeint, hab es also mit "simply" ersetzt.

2022-01-10 08:21 UTC, raphael-adam commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +Here the values "contact" and "receiver" are variable. When e.g. using "warehouse" and "sender", the warehouse will be filtered.
Ich habe es in der REST Doku mit geschweiften Klammern markiert, dass hier im Namen Variablen ersetzt werden müssen. Es ist auch im Text dort beschrieben, dass das ausgetauscht werden muss. Reicht das?

![Bildschirmfoto 2022-01-10 um 09 20 09](https://user-images.githubusercontent.com/19149728/148735936-6804556a-623f-4a98-9647-6d73cb722c95.png)

2022-01-10 08:23 UTC, jawendel commented on docs/en-gb/modules/rest-api-guides/pages/order-search.adoc
> +Here the values "contact" and "receiver" are variable. When e.g. using "warehouse" and "sender", the warehouse will be filtered.
Ja, ich finde das reicht. Sollten Leser:innen Schwierigkeiten haben, kann man es ja immer noch anpassen. Mir war nur wichtig, dass es irgendwo steht und zu finden ist.

2022-01-10 08:30 UTC, jawendel approved these changes

2022-01-10 14:07 UTC, estafilarakis approved these changes

2022-01-12 10:49 UTC, merged